sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gcc-4.9
            - cmake
            - cmake-data
      env: CXX_COMPILER=g++-4.9 C_COMPILER=gcc-4.9 DOC=true
    - compiler: gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - cmake
            - cmake-data
      env: CXX_COMPILER=g++-5 C_COMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - cmake-data
      env: CXX_COMPILER=clang++-3.7 C_COMPILER=clang-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
script:
  - ./dev/travis-run-tests.sh
after_success:
  - /bin/bash export_doc.sh